# Generated by Django 4.2.11 on 2024-04-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_piditt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiderazgoFemenino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('total_mujeres', models.IntegerField()),
                ('total_hombres', models.IntegerField()),
            ],
        ),
    ]
