# Generated by Django 4.2.11 on 2024-04-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_liderazgofemenino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liderazgofemenino',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
    ]
