# Generated by Django 4.2.11 on 2024-04-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_liderazgopublicaciones_alter_liderazgofemenino_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosITT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('total_mujeres', models.IntegerField()),
                ('total_hombres', models.IntegerField()),
                ('total_proyectos', models.IntegerField()),
            ],
        ),
    ]
