# Generated by Django 4.2.11 on 2024-06-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_proyectositt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FONDEF_categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('categoria', models.CharField(max_length=200)),
                ('total_mujeres', models.IntegerField()),
                ('total_hombres', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FONDEF_financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('financiamiento', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=200)),
            ],
        ),
    ]
