# Generated by Django 4.2.13 on 2024-06-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fondef_categorias_fondef_financiamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicos_acreditados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('total_mujeres', models.IntegerField()),
                ('total_hombres', models.IntegerField()),
                ('programa_postgrado', models.IntegerField()),
            ],
        ),
    ]
