# Generated by Django 4.2.13 on 2024-06-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_academicos_acreditados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academicos_acreditados',
            new_name='Academicosdap_acreditados',
        ),
    ]
