# Generated by Django 4.2.13 on 2024-06-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_academicos_acreditados_academicosdap_acreditados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fondef_financiamiento',
            name='financiamiento',
        ),
        migrations.RemoveField(
            model_name='fondef_financiamiento',
            name='sexo',
        ),
        migrations.AddField(
            model_name='fondef_financiamiento',
            name='financiamiento_hombres',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondef_financiamiento',
            name='financiamiento_mujeres',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondef_financiamiento',
            name='financiamiento_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicosdap_acreditados',
            name='programa_postgrado',
            field=models.CharField(max_length=200),
        ),
    ]
