# Generated by Django 4.2.13 on 2024-06-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_academicos_acreditados_academicosdap_acreditados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicosdap_acreditados',
            name='programa_postgrado',
            field=models.CharField(max_length=200),
        ),
    ]
