# Generated by Django 4.2.13 on 2024-06-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_fondef_financiamiento_financiamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicosdap_tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_academico', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=200)),
                ('magister_aca', models.IntegerField()),
                ('magiser_pro', models.IntegerField()),
                ('doctorado', models.IntegerField()),
                ('esp_medicas', models.IntegerField()),
                ('esp_odonto', models.IntegerField()),
                ('otras_esp', models.IntegerField()),
            ],
        ),
    ]
