# Generated by Django 4.2.13 on 2024-06-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_academicosdap_tipos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicosdap_tipos',
            old_name='doctorado',
            new_name='claustro',
        ),
        migrations.RenameField(
            model_name='academicosdap_tipos',
            old_name='esp_medicas',
            new_name='colaborador',
        ),
        migrations.RenameField(
            model_name='academicosdap_tipos',
            old_name='esp_odonto',
            new_name='nucelo',
        ),
        migrations.RenameField(
            model_name='academicosdap_tipos',
            old_name='magiser_pro',
            new_name='permanente',
        ),
        migrations.RenameField(
            model_name='academicosdap_tipos',
            old_name='tipo_academico',
            new_name='tipo_programa',
        ),
        migrations.RenameField(
            model_name='academicosdap_tipos',
            old_name='magister_aca',
            new_name='visitante',
        ),
        migrations.RemoveField(
            model_name='academicosdap_tipos',
            name='otras_esp',
        ),
    ]
